### PR TITLE
Nested Property for nested rules/@rule

### PR DESCRIPTION
**Pull request by notoriousb1t**
This PR aims to solve this issue #40 .  If accepted, it should be considered a minor/major change since it breaks nesting selectors next to properties.

It adds the following "nested" property to allow nesting selectors:
```ts
style({
  nested: {
    '@media screen': {
        color: 'red'
     }
  }
})
```

It adds shorthands for simple pseudo-selectors so they can still be used without going into a "nested" property.

```ts
style({
    color: 'blue',
    '&:active': {
      color: 'red' 
    }
});
```

And adds several CSS Properties needed to compile and pass the existing tests

* [ ] Check that `nested` actually type checks https://github.com/Microsoft/TypeScript/issues/12584

### CODE REVIEW

**Comment by basarat** [comment]
> It adds shorthands for simple pseudo-selectors so they can still be used without going into a "nested" property.

I feel like this will only result in confusing and difficult to debug errors. Although I did try to do the same (there were a few in NestedCSSProperties) I found people at work and in the wild e.g. https://github.com/staltz/matrixmultiplication.xyz/blob/8f1d761f5e49e2ccd92a1760b07ec6c7a72fbd9e/src/App/styles.ts#L39-L41 using all sorts of selectors with opinions on formatting ... more than the ones I used. 

I'll remove that so there is only one way to do things without special cases being documented / maintained elsewhere. 

> it should be considered a minor/major change since it breaks nesting selectors next to properties.

This has been the biggest concern at the back of my head and the reason I didn't go with `v1` yet. So happy to go `v1` once we are settled on this :)

**Comment by notoriousb1t** [comment]
I can't argue with the pseudo-selector thing.  I put that in there as an attempt to break as little code as possible, but I can see how it would be confusing if someone did that and expected '& > *' to work.

I also added a special function for fontFace since it has properties directly and some of them appear to be specific to declaring fonts.

**Comment by basarat** [comment]
> I also added a special function for fontFace

Looks good. Thanks. Its a common enough task to deserve its function just like we have for `keyframes` :rose:

**Comment by basarat** [comment]
@notoriousb1t Just need a 👍 from you. I'll merge + deploy + write release notes + update website :rose:

**Comment by basarat** [comment]
Hmm.. It doesn't error on a typo still 

image

**Comment by basarat** [comment]
Suspect TypeScript type system is getting confused by circular types. Will try and narrow down an issue report :rose:

**Comment by basarat** [comment]
I created an issue https://github.com/Microsoft/TypeScript/issues/12566 . Suspect the answer will be *no*. 

Also had a discussion with colleagues at work and they prefer a `nested()` function as its easier to write without erroring

```ts
declare var style: any; 
declare var nested: any;

// A 
style({
    color: 'grey',
    nested: {
        '&:hover': {
            color: 'red'
        }
    }
})

// B
style(
    { color: 'grey' },
    nested('&:hover', {
        color: 'red'
    })
)
```

Had people struggle with `A` and they would write stuff like the following failing to manage brackets correct / and forgetting to write the selector. 

```
style({
    color: 'grey',
    nested: {
       color: 'red'
    }
})
```

also we wouldn't need to teach people `{nested({[code]:style}}` computed property syntax as `nested(code,style)` is something that people understand from ES5.

I'll work on that soon :rose:

**Comment by notoriousb1t** [comment]
There is no reason we can't do both 😉 

```ts
function nested(code, props) {
   return {
      nested: {
         [code]: props
      }
   }
}

style(
    { color: 'grey' },
    nested('&:hover', {
        color: 'red'
    })
)
```

**Comment by basarat** [comment]
Will hold off till TS teams comes back on the error 🌹

**Comment by notoriousb1t** [comment]
Yeah.  Trying to replicate CSS in a formal type system has resulted in some pretty interesting types.  I think we might be pushing the boundaries a little bit here.

**Comment by basarat** [comment]
So the code we have works fine if `strictNullChecks` is false: 

image

@vladima did the analysis https://github.com/Microsoft/TypeScript/issues/12584 and already posted a fix for strictNullChecks as well : https://github.com/Microsoft/TypeScript/pull/12595 

@notoriousb1t I say we can merge this. Hurray for `{nested:{'&:hover':obj}}`.  Thanks for your patience and standing your ground on excellent API design :heart:

**Comment by notoriousb1t** [comment]
Hurray! 😄

**Comment by basarat** [comment]
The changes are covered here : https://github.com/typestyle/typestyle/issues/43. Will try to wait for https://github.com/Microsoft/TypeScript/pull/12595 to be merged and think through anything else that needs to be done before 1.0 :rose:

**Pull request merged**
