### PR TITLE
FontFace type fixed, Added backgroundSize & content properties to CSSProperProperties interface

### PR DESCRIPTION
**Pull request by Hapet95**

### CODE REVIEW

**Comment by notoriousb1t** [comment]
Thank you for helping make our type defs better 😄   I have a few notes before we can merge.

- Please change content to CSSValueString
- Please change background-size to 'auto' | 'cover' | 'contain' | CSSLength | CSSPercentage | CSSGlobalValue

**Comment by Hapet95** [comment]
Sorry for mistake)) done @notoriousb1t ! :)

**Comment by notoriousb1t** [comment]
Cool.  We are ready to merge 😄

**Comment by notoriousb1t** [comment]
released 0.14.4

**Comment by Hapet95** [comment]
Cool! thanks! And if it's not difficult please see my last  added issue :)

**Pull request merged**
