### PR TITLE
add media-query to string method

### PR DESCRIPTION
**Pull request by devdoomari**
add media-query to string method.

### CODE REVIEW

**Comment by basarat** [comment]
Thanks :rose: ! We want to keep the API surface small. Is there a use case for it?

**Comment by devdoomari** [comment]
Here's the edge case:

```typescript
export const _step123: NestedCSSProperties = {
  $nest: {
    '&::after': {
      ...media(OVER_PHONE, {
        width: 2, height: 100,
      }),
      $nest: {           // can't add more to '$nest' here, as ...media( ...) can be overwritten.
      },
    }
  }
}
```
here, as media() returns
```typescript
{ 
  $nested: {
    <mediaQueryString>: { ... }
  }
}
```
format, I can't add more properties for $nested.

**Comment by basarat** [comment]
> I can't add more properties for $nested.

You can use `typestyle.extend`. Indeed that function isn't documented and should be : http://typestyle.io/#/core.  Created https://github.com/typestyle/typestyle/issues/123 :heart: 

Please close if that is the only use case :rose:

**Comment by devdoomari** [comment]
yep typestyle.extend will do! closing : )

**Pull request closed without merging**
