### PR TITLE
Use csstype for standardized CSS property definitions

### LINKED ISSUE #200: Take out css definitions to separate lib
Typestyle has good css props typings with docs. This could be also used for some other libraries related to css.

One of the use cases: https://github.com/snabbdom/snabbdom/issues/339

What do you think about taking out css props definitions to separate lib, and reuse it in typestyle?

PS. This is a successful issue number =)

### PR DESCRIPTION
**Pull request by pelotom**
Resolves #200.

That issue was closed with the comment https://github.com/typestyle/typestyle/issues/200#issuecomment-375135331:

> If someone else creates an excellent type definition that receives consensus among CSS in JS projects we can definitely consider taking it as a dependency 🌹

I believe [`csstype`](https://github.com/frenic/csstype) is that library. As of today it has been adopted by `@types/react`, `@types/jss` and Glamorous:
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24688
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24078
- https://github.com/paypal/glamorous/issues/408

So consensus is building, and it would be great if TypeStyle could be a part of building it!

### CODE REVIEW

**Comment by pelotom** [comment]
Ugh, did this work on a very outdated version of `master`. Will rebase provided there’s interest from @basarat.

**Comment by pelotom** [comment]
> I have in-principle support for this. The CSS type definitions cause the highest maintenance load for this project, so pooling efforts with other communities is appealing.

Great! 😄

> A couple of nits:
> 
> - It’s not clear to me if this will be a breaking change or not, presumably there’ll be some differences (whether correct or not) that will require consumers to make some tweaks

Yeah, I think we'll want to be very careful, and perhaps keep the old definitions around long enough to verify them against the new ones. It would be a good test to look through the type errors on

```ts
function assign(properties: CSSProperties): CSS.Properties {
  return properties;
}
```

and make sure that they all make sense, i.e. that they are only due to the old typings being too loose. I've already seen from a cursory inspection that there are cases where csstype is missing some things that typestyle has, most notably SVG properties and several vendor prefixes. An interim solution  for missing properites might be to use a string index signature as fallback, as was done with `@types/react`, but maybe that would be considered a step backward for TypeStyle.

> - The types from csstypes don’t seem to have comments from MDN yet

Yeah, that would be nice. @frenic what do you think?

**Comment by pelotom** [comment]
> It’s not clear to me if this will be a breaking change or not, presumably there’ll be some differences (whether correct or not) that will require consumers to make some tweaks

To be clear, I think there definitely _will_ be breaking changes, but my hope is that they should only be situations where incorrect properties/values were previously accepted that no longer are.

**Comment by basarat** [comment]
> So consensus is building, and it would be great if TypeStyle could be a part of building it

Personally I want to be on the *tail* end of the adoption. There are some changes happening at my work that mean I can't have TypeStyle being stale or unstable at all. At least not on my own accord. 

I am happy with any of the owners of the project supporting / maintaining this. The last thing I *owned* was the domain and I let it expire so that it can be `github.io` and remove any special privilege I have on this project :rose:

**Comment by frenic** [comment]
> The types from csstypes don’t seem to have comments from MDN yet

Comments could be auto generated with data such as inheritance, initial values, browser compatibility and stuff like that. But property descriptions does unfortunately not exist in MDN data and I haven't found anything in any of their other public repositories either. We would have to add and maintain them manually which I'm not too fond about. Have you composed all of your property descriptions manually for TypeStyle or have you copied them from somewhere?

**Comment by notoriousb1t** [comment]
The property descriptions are paraphrased from MDN and then we include a @see link to point directly there.

I am not fond of creating a breaking change to do this. I support separating our css into a separate project, but I would rather not disrupt our users to do it. If we accept this change I think we have to do a major version.

**Comment by pelotom** [comment]
Updated the PR using the latest CSSType, [which now includes, for every property, jsdocs with compatibility tables and links to MDN data](https://github.com/frenic/csstype/pull/45). I have documented the remaining discrepancies between TypeStyle and CSSType here:

https://github.com/frenic/csstype/issues/20

I believe for the most part these remaining discrepancies are where TypeStyle is using deprecated or not-fully-supported properties or keywords, or where it is using looser typing than it should be. @basarat, perhaps you'd like to try `npm link`ing this branch and see if it's compatible with your projects?

**Comment by pelotom** [comment]
Also, [add Glamorous to the list of projects using CSSType](https://github.com/paypal/glamorous/issues/408) 😄

**Comment by bradleyayers** [comment]
I'm going to build and use this on a couple of projects and see how it goes in practice.

**Comment by pelotom** [comment]
> - fontWeight no longer supports number (solve via explicitly typing with types.NestedCSSProperties)
> - flexDirection no longer supports string (solve via explicitly typing with types.NestedCSSProperties)

These shouldn't just allow arbitrary `number`s/`string`s, should they? They each have a finite set of valid values which can be enumerated.

>-moz-osx-font-smoothing no longer supported

My understanding is this is a non-standard property:
- https://gist.github.com/y0ssar1an/bb95223148e486acbe7a
- https://github.com/woocommerce/storefront/issues/698

**Comment by bradleyayers** [comment]
> These shouldn't just allow arbitrary numbers/strings, should they? They each have a finite set of valid values which can be enumerated.

Correct, I just mentioned it to be exhaustive. The narrowed types are an improvement. 

> My understanding is this is a non-standard property:

Yep, I'll probably remove this one from my project.

From my perspective the only blocker is the csx incompatibility. Perhaps just a major version bump to take TypeStyle to 2.0.0 followed by an update to csx. Have you taken a look at csx to see if it can just pull in types from csstype too?

**Comment by pelotom** [comment]
>From my perspective the only blocker is the csx incompatibility. Perhaps just a major version bump to take TypeStyle to 2.0.0 followed by an update to csx. Have you taken a look at csx to see if it can just pull in types from csstype too?

I haven't looked in depth at csx, but yes, I think it should probably also use types directly from `csstype` as necessary. I debated trying to maintain backwards compatibility by having TypeStyle export a bunch of aliases like

```ts
export type CSSBox = CSS.Box;
```

but decided against it because it felt odd to be exporting a bunch of types that were not needed by TypeStyle itself. Also some of them have no direct analog in csstype, for example `CSSSideOrCorner`. It feels like these types should just be defined in csx, what do you think?

**Comment by frenic** [comment]
Syntax aliases like `CSS.Box` are highly dependent on the [data from MDN](https://github.com/mdn/data/blob/33482ae3cba9a1a16a1e18f79921b97b4d8ec6e1/css/syntaxes.json#L50-L52) and some of them dissolves if they are too small. So it's a bit risky to use them. Unless:

1. There're some kind of tests (or at least type checks) of syntax aliases in csstype that can be explicitly used by other libraries to make sure they wont break anything
1. Some syntax aliases are hard coded but still uses the syntax from MDN like I've done [with the `all` property](https://github.com/frenic/csstype/blob/master/src/properties.ts#L51) that will fail the build of csstype if they are e.g. renamed or divided into several syntax aliases

**Comment by bradleyayers** [comment]
Pushing these types out of TypeStyle and into csx makes sense. Keeping them in TypeStyle seems like unnecessary indirection, and anyway the source of truth should be csstype.

**Comment by bradleyayers** [comment]
It sounds like having a look at csx and seeing what would be involved in migrating it to csstype is a sensible next step. For TypeStyle I think this PR should be released in a major version, but I think we should have a compatible version of csx be available around the same time.

**Comment by pelotom** [comment]
@bradleyayers Ok, I don't use csx so I'm not sure I'm the best person to try to figure out which things to use from csstype vs. defining there.

**Comment by notoriousb1t** [comment]
I am not comfortable moving the project or csx over to csstype at this point in time.  It seems very early in the adoption process of csstype (stars, download history, and one maintainer) and updating the types in this project isn't a big deal maintenance wise.  

I can only see how our users might be hindered waiting for a 3rd party to update their definitions, and not any benefit to the codebase here as a result.

I guess what I am saying is, what are we trying to accomplish by outsourcing the types?

**Comment by pelotom** [comment]
> I guess what I am saying is, what are we trying to accomplish by outsourcing the types?

I don't know what to tell you except that by linking my app to the version of TypeStyle built on this branch, I caught several longstanding bugs in my styles.

The motto of TypeStyle is "Making CSS Typesafe", but as of right now several CSS-in-JS libraries have leapfrogged TypeStyle in this respect, simply by virtue of abandoning their home-grown CSS typings for CSSType. You say "updating the types in this project isn't a big deal maintenance wise" but that glosses over the fact that the types are at this moment very flawed: there's hundreds of obsolete/non-standard properties and hundreds of property values which are overly loose or completely unsafe (typed as `any`). Until CSSType the CSS typings maintained in this project were far and away the best I had seen anywhere, but that's no longer the case by a long shot.

> I can only see how our users might be hindered waiting for a 3rd party to update their definitions

You can always choose to maintain an augmented set of properties on top of what CSSType provides; simply add them to the `CSSProperties` interface.

**Comment by pelotom** [comment]
Just one more thing on the subject of maintenance: CSS is a moving target, and the only right way to maintain types for it is through automation, which is what @frenic has done. _Nobody_ should be maintaining CSS typings in the way that that this and other projects have been doing, let the robots maintain them!

**Comment by notoriousb1t** [comment]
When discussing ideas, I find it helpful not to discuss things in absolutes.  Using things like "right way" and "nobody" do not advance the conversation.  The fact that the types need updating is a good reason to update them.  I don't know that it is a good reason to move it out of the project.

Here are my primary concerns:

1. The project is maintained by one individual (not an organization).  It would be preferable if a member of TypeStyle was also a maintainer on the other project.  People drop out of open source all the time.  This project has 36k downloads a month.  Many people depend on it (including myself and other maintainers) It feels irresponsible to make this kind of change without some assurances.

2. Even obsolete properties are required by users in production. Maintaining a separate list of properties seems like a half answer.  I get the desire to do Modern - 2 support, but that isn't the reality of all. Punishing our users because the browsers released features under prefixes, seems pretty unfair, especially since CSS ignores things it can't understand.  Strictly speaking, an obsolete property is not a bug, it is unnecessary code in modern browsers.

3. I'm not 100% sure the typing system will catch everything, but I haven't had time to kick the tires yet.  This is on me, so I will download this and see if it catches typed errors in nesting properly.

I am not diametrically opposed to using csstype, but at a certain level of lib popularity, you have consider breaking changes a big deal.  There is a reason we held off of releasing a 1.0.0 version for a long time.

**Comment by pelotom** [comment]
> The project is maintained by one individual (not an organization). It would be preferable if a member of TypeStyle was also a maintainer on the other project.

That seems reasonable to me, but it's up to @frenic. 

> People drop out of open source all the time.

It would also be trivial to fork CSSType if that happened.

> This project has 36k downloads a month. Many people depend on it (including myself and other maintainers) It feels irresponsible to make this kind of change without some assurances.

CSSType has 1.5 million downloads per month. Don't be fooled by GitHub stars, it is already heavily depended upon. This package isn't going anywhere; if @frenic disappeared tomorrow, a replacement would spring up in no time.

> Even obsolete properties are required by users in production. Maintaining a separate list of properties seems like a half answer.

Why is it not a full answer?

**Comment by bradleyayers** [comment]
> CSSType has 1.5 million downloads per month. Don't be fooled by GitHub stars, it is already heavily depended upon.

I feel some reassurance that [CSSType is a dependency of `@types/react`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L24) which may also explain this number.

> The project is maintained by one individual (not an organization). It would be preferable if a member of TypeStyle was also a maintainer on the other project.

This is a good point, I'd like to see the maintainers expander a bit here.

> I don't know what to tell you except that by linking my app to the version of TypeStyle built on this branch, I caught several longstanding bugs in my styles.

I didn't have an experience as impressive as that, but what did motivate me to try it out was finding a property missing in TypeStyle that I needed to open a PR for, but felt like the csstype approach might alleviate that entire source of bugs.

**Comment by notoriousb1t** [comment]
Looking in depth at csstype has given me some confidence in the approach.  Since they are effectively reformatting the json files from https://github.com/mdn/browser-compat-data, there is reason to consider the underlying types reliable.

Outside of the single maintainer issue, my only other reservation is that we would lose descriptions in our jsdocs.  Many of our descriptions are either from MDN directly or were authored/modified to explain each property.  The current jsdocs in csstype do not describe what the property does.   csstype has the default value and a compatibility table.  

I will raise an issue on csstype for css property descriptions.

**Comment by notoriousb1t** [comment]
@frenic and I worked through a solution on property summaries.  That has been merged in and I believe the definitions are now superior to our definitions in every way.

Next is getting csstips and csx to use csstype.  Once we get that squared away, I am on board.

**Comment by frenic** [comment]
Just published as `csstype@2.5.0`

**Comment by notoriousb1t** [comment]
CSX has a PR locked and loaded to be merged and published.  

Because csstips uses typestyle as a direct dependency, I think we have to merge this PR before we can update that one.  @basarat, are you ok with moving forward with this?

**Comment by basarat** [comment]
> Because csstips uses typestyle as a direct dependency, I think we have to merge this PR before we can update that one. @basarat, are you ok with moving forward with this?

:+1: :rose:

**Comment by pelotom** [comment]
Thanks for championing this @notoriousb1t!

**Pull request merged**
