### PR TITLE
Update free-style to version 3.1.0 and other deps updates

### PR DESCRIPTION
**Pull request by notoriousb1t**
Closes #346

### CODE REVIEW

**Comment by notoriousb1t** [comment]
@basarat, could you spot check this for me? I haven't made significant changes to this codebase in a while and I haven't had any opportunity to do React development since I joined Google.

I actually meant to just hit some merge buttons to clear my inbox, but the free-style api changed and many of our deps were pretty out of date. It looks like this also closes our other PR for $debugName since free-style depends on node environment now and doesn't have a parameter for this. This fixes that request.

Let me know what you think. If this looks good, I'll up the major version and see what changes need to be made to the docs site.

**Comment by basarat** [comment]
> Let me know what you think. If this looks good, I'll up the major version and see what changes need to be made to the docs site. 

Looks good :+1:

**Comment by basarat** [comment]
@notoriousb1t from commit : https://github.com/typestyle/typestyle/commit/5e73b7edb35ee6a222b4df9d125c0bc6a95d5c7f

> Due to these changes, we should treat this as a major version.

I disagree. I don't see any breaking changes for our consumers : our `$debugName` still works, our `$unique` still works. 

If you are okay I'll cut a minor release to include this along with other changes (that are also minor) :+1:

**Comment by notoriousb1t** [comment]
Perhaps I was being overly cautious here. SGTM 👍

**Comment by basarat** [comment]
Released 2.1.0 :rose:

**Pull request merged**
