### PR TITLE
Feature/stylesheet function

### PR DESCRIPTION
**Pull request by codeandcats**
## Appreciation
Love the library guys! ❤️ I wanted to contribute back a pattern I end up repeating in my projects. This could live in userland though I feel like it would be a small but useful additional to this great lib.

I didn't see a contribution guide but have tried to observe and follow all conventions. Two space indentation, JavaDoc comments, unit tests.

## Adds a `stylesheet` function to TypeStyle.

Lets you pass in an object with multiple classes that you wish to generate and returns an object with the generated class names using the property names as each $debugName. Very convenient for declaring all the styles you need for a component in one hit and getting back meaningful class names.

```typescript
export const classes = stylesheet({
  warning: {
    color: 'red'
  },
  success: {
    color: 'green'
  }
});
```

`classes` will equal:
```
{
  warning: 'warning_f1jvcvsh',
  success: 'success_fmubem1'
}
```

### CODE REVIEW

**Comment by basarat** [comment]
@codeandcats Thanks! Highly appreciate your contribution and kind words. 

That said the work of the function can be offloaded to the TypeScript language feature *namespaces*. Also the definition for the style function leaves open chances of typos e.g. `classes.sucess` would return `undefined` but not raise any compile time error. 

Closing for the same reasons that `styleSheet` was closed https://github.com/typestyle/typestyle/issues/137#issuecomment-293451554 

Again, closing primarily cause its a language feature we don't need to reinvent :rose:

**Comment by codeandcats** [comment]
Hey @basarat, thanks for responding.

Did you look at the implementation? The styles function takes advantage of TypeScript 2.1's Mapped Types so that it returns an object typed with the exact property names as strings, thus preventing typos at compile time.

Remember the other big advantage of this is that it automatically returns meaningful class names for development. Please don't discount this feature. Having used this library I've found it quite painful at times searching the dom. Having meaningful class names is a huge improvement to the developer experience, without the dev having to add data-blah attributes just to help with debugging.

I sincerely hope you will reconsider this feature.

**Comment by codeandcats** [comment]
CC @james-erekson-sportsbet

**Comment by james-erekson-sportsbet** [comment]
Yeah, +1 from me. I'm definitely keen to use this kind of feature. The one you've written is extremely similar to mine, with the extra mapped type. We did consider doing that mapped type as well (quite similar to React Native's StyleSheets). There's a bit of extra boilerplate, but it does address type safety.

We've already implemented the styles/styleSheet concept in our user code, even though it didn't get added to the library.

I'm definitely a fan of mixing in the $debugName as well; my devs might mutiny to bring back SASS without it, as it's essentially impossible to read the hashed class names while debugging.

The $debugName isn't the only feature I can think of that could use the styleSheet concept either...

**Comment by codeandcats** [comment]
Cheers @james-erekson-sportsbet. I think `stylesheet` is a better name for the function too, I'd probably want to rename to that if this were to make it in.

**Comment by james-erekson-sportsbet** [comment]
On closer inspection, your typedef is simpler than react native's StyleSheet because you don't have to explicitly declare a type for each key in your stylesheet; since they're all NestedCSSProperties, looks like it's able to infer them implicitly. So there isn't any extra boilerplate.

**Comment by codeandcats** [comment]
I've pushed a commit to rename the `styles` function to `stylesheet`.

**Comment by codeandcats** [comment]
Actually the mapped type result was a recent addition in my code and I just realised that while the output is now strongly typed, the input is now weakly typed.

e.g. This works as expected:
```typescript
const classes = stylesheet({
    warning: {
        color: 'red'
    }
});

console.log(classes.warning); // <-- works as expected
console.log(classes.warnign); // <-- warning spelt wrong, compiler error as expected
```

However, in doing so, we've lost proper checking on the input:
```typescript
const classes = stylesheet({
    warning: {
        colour: 'red' // <-- color spelt wrong, no compiler error,
        backgroundColor: 333 // <-- number type invalid, no compiler error
    }
});
```

The problem is one needs to know the exact type of the input in order to map the output type, therefore the input needs to be generic. But we still need to constrain the input type to this interface:
```
interface ClassesWithNestedCSSProperties {
	[className: string]: types.NestedCSSProperties;
}
```

Unfortunately the only way I know how to do that is with a generic constraint, i.e. `T extends ClassesWithNestedCSSProperties` and I think the extends part is the problem. We're no longer saying T is exactly this interface, we're saying it extends this interface and so typescript no longer assumes every property is a `NestedCSSProperties`.

I must admit, unfortunately, without this proper typing, I don't think this is ready to be pulled in. 😞 

I fear it may not be possible in the current state of TypeScript. I don't know. Any suggestions on how to crack this nut? Would be great to work this out if it is possible.

**Comment by codeandcats** [comment]
lulz, nevermind. After that lengthly writeup I just worked it out. Changed from `classes: T` to `classes: T & ClassesWithNestedCSSProperties`. 🙄 

Will push the fix shortly. 😸

**Comment by codeandcats** [comment]
Sigh, unfortunately the input is still not as strong as I'd like...

```
const classes = stylesheet({
    warning: {
        colour: 'red' // <-- color spelt wrong, no compiler error, boo!
        backgroundColor: 333 // <-- number type invalid, compiler error, yay!
    }
});
```
🤔

**Comment by james-erekson-sportsbet** [comment]
The boilerplate approach I was talking about would solve both issues.
```
interface Styles {
  warning: types.NestedCSSProperties,
  success: types.NestedCSSProperties
}
const classes = stylesheet<Styles>({
  warning: {
    color: 'red'
  },
  success: {
    color: 'green'
  }
});
```
But this doesn't seem like an optimal solution to me, because you then have to explicitly declare everything upfront.

**Comment by codeandcats** [comment]
Ah I see what you mean @james-erekson-sportsbet.

Expanding on your approach, I notice that this will work too:
```typescript
import { stylesheet, types } from 'typestyle';

const classes = stylesheet<types.ClassesWithNestedCSSProperties>({
    warning: {
        colour: 'red' // <-- color spelt wrong, compiler error, yay!
        backgroundColor: 333 // <-- number type invalid, compiler error, yay!
    }
});
```

So you don't have to declare an interface at least, just import the types and pass in `ClassesWithNestedCSSProperties` and it works exactly as expected. Its still not ideal having to pass in the interface if you want to pick up on typos in property names, but I think its definitely workable. I'd still love to see this get in (and would be happy to update documentation).

Thoughts?

**Comment by james-erekson-sportsbet** [comment]
This approach would be fine with me, looks like the original issue has re-emerged though. The object coming back no longer seems strictly typed:
```
const classes = stylesheet<types.ClassesWithNestedCSSProperties>({
    warning: {
        color: 'red'
    }
});

console.log(classes.warning); // <-- works as expected
console.log(classes.warnign); // <-- still no compiler error :(
```

**Comment by codeandcats** [comment]
Dang, you're absolutely right.

Hmm, I'll revisit this tonight/over the weekend and see if I can figure this out.

**Comment by codeandcats** [comment]
Sorry guys, I tried a bunch of techniques and haven't been able to get the strong typing to work on input and output without the use of James' technique of declaring the interface upfront and explicitly passing that in as the generic type, which as James' points out is less than optimal.

Without a more convenient way of strongly typing both the input and output I can't recommend pulling this into the library, so I'm going to close this for now. Hopefully TypeScript will solve this limitation some day. 😞

**Comment by codeandcats** [comment]
Hey guys, I am excited to say I think I've got the typing of this stylesheet function working perfectly now so it should catch all the following consumer coding mistakes at compile time:
- Misspelled/unknown css property names
```
const styles = stylesheet({
  warning: {
    backgroundColour: 'red' // <-- Error, "colour" should be spelt "color"
  }
});
```
- Invalid property values
```
const styles = stylesheet({
  warning: {
    backgroundColor: 255 // <-- Error, backgroundColor cannot be a number
  }
});
```
- Misspelled/unknown class names
```
const styles = stylesheet({
  warning: {
    backgroundColor: 'red'
  }
});

alert(styles.warming); // <-- Error, typo: should be "warning" not "warming"
```
- Correct typing of class names
```
const styles = stylesheet({
  warning: {
    backgroundColor: 'red'
  }
});

alert(styles.warning * 5); // <-- Error, cannot perform arithmetic on a string
```
With that I've reopened this PR in the hopes it will make it in. ❤️

**Comment by basarat** [comment]
I am okay with this :rose:

Ofcourse I will verify locally before pushing, but still @notoriousb1t want your approval / thoughts if any :heart:

**Comment by notoriousb1t** [comment]
I think the feature makes sense and doesn't add a lot of code weight. I have warmed up to it since its initial proposal and think it would provide better structure if for some reason it isn't used with TypeScript.

**Comment by basarat** [comment]
Note to self. Add docs here post merge : https://github.com/typestyle/typestyle.github.io/blob/source/src/docs/core.md#tip-code-organization

**Comment by basarat** [comment]
image

No autocomplete? :(. Perhaps I missed something. It might be TypeScript's weakness, but autocomplete is a big positive with TypeStyle that I don't want anyone to live without :rose:

**Comment by codeandcats** [comment]
Hmm, that's curious and frustrating. 🤔 

Interestingly when I package the code into [a single unit](https://gist.github.com/codeandcats/0a5580c18a0a82636200bdfa297b2fda) for the [TypeScript Playground](https://www.typescriptlang.org/play/) the auto-complete works fine...

**Comment by codeandcats** [comment]
Sorry guys, I feel my greying hair has desaturated and lightened by at least 15% over the course of this PR trying to get this feature typed right. 😩

As much as I’d love to see this feature make it in, I don’t think I’ve got any drive left to 1. discover why TypeScript is not providing auto-complete and/or 2. come up with a solution that solves it (if it even exists) while not breaking all the other key criteria.

The typings will still break at compile-time if you try to use them wrong, but I totally understand if you would rather not merge this in. Auto-complete is a nice feature many devs, especially TypeScript ones, are used to. 😌

**Comment by notoriousb1t** [comment]
I've taken a long look at this issue and autocomplete is not working when trying to complete a word but will work if you CTRL+Space in an empty block.  I believe the issue is that we are using a type that indexes over the key of a generic which returns a weak type.  In some cases, TypeScript understands that we are autocompleting a NestedCSSProperties, and in others it thinks it is a typical literal.  This is a head-scratcher as it appears the types are setup correctly.  I'm not sure how to present this as an issue to TypeScript, because I don't really know why the tooling isn't working.

I have a suspicion that auto-complete would be better if we used an interface, but I don't know how to do the keyof indexer in an interface.

**Comment by mattoni** [comment]
@codeandcats referenced this MR in a similar issue for ya over at the typescript repo. This interests me because I both extensively use a similar method to your stylesheet function, and have run into (but ultimately just lived with) the issue of types not autocompleting when the mapped type is inferred from the function return. It's driven me nuts lol.

**Comment by notoriousb1t** [comment]
@basarat, I know this has been sitting for a while, but I think we should add this.  I tested this PR and made some commits to the branch https://github.com/typestyle/typestyle/tree/pr/144.  

I think that the benefits of adding stylesheet outweigh the lack of autocomplete in one particular circumstance:  when you have an empty object and press CTRL + SPACE (or whatever triggers autocomplete), weak typing assumes any object.  If you start typing before opening autocomplete, autocomplete works correctly.  Regardless of how it is typed, TypeScript correctly identifies issues such as using an incorrect display type or using a non-existent property name.
 
I think this doesn't add much in terms of maintenance costs and would make authoring CSS easier at scale.

**Comment by basarat** [comment]
@notoriousb1t go for it. Release as you want :rose:

**Comment by notoriousb1t** [comment]
@codeandcats,  I will put out a minor release version tonight for this after I updated the TypeStyle docs.

**Comment by notoriousb1t** [comment]
Released in 1.7.0.  https://typestyle.github.io/#/core/-stylesheet-

**Pull request merged**
