### PR TITLE
Add missing grid related CSS properties

### PR DESCRIPTION
**Pull request by bradleyayers**

### CODE REVIEW

**Comment by basarat** [comment]
@bradleyayers I've given you commit access https://github.com/typestyle/typestyle/invitations and also added you on npm. 

You can add simple type def fixes and release them yourself:

* Commit + Push 
* `npm version patch` from project root (will automatically take care of releasing + git pushing).

Did this so it doesn't block your team for simple things like this :rose:

**Comment by bradleyayers** [comment]
Thanks! I've released 1.3.6. What's the situation with CHANGELOG.md, is that deprecated in favour of Github's releases feature?

**Comment by basarat** [comment]
> What's the situation with CHANGELOG.md, is that deprecated in favour of Github's releases feature?

I used the changelog, notoriousb1t used the github releases. For the past few `patches` we have used neither. Git commit message are all for now. I like to think TypeStyle is done till something *truly better* comes along, meanwhile TypeScript keeps gaining popularity so the next thing might be in TypeScript so we don't need to recreate a TypeScript first experience :rose:

**Comment by notoriousb1t** [comment]
It's true. I think that at this point there is little we could add to the library that would bring great value.  It kind of just works.  Outside of type definitions and documentation, I don't see much else to even add to a change log.  Personally, I'm pretty happy with TypeStyle as a user.  It is my defacto way to deal with CSS in React and Vue.  

I agree that git commit messages are probably enough unless we need to make major changes.

**Pull request merged**
