### PR TITLE
Updates to css.d.ts

### PR DESCRIPTION
**Pull request by notoriousb1t**
Added animation timing functions and animation direction types.  Changed transitionTimingFunction to point to CSSTimingFunction.

### CODE REVIEW

**Comment by basarat** [comment]
Thanks! Released with 0.2.8 :rose:

**Comment by notoriousb1t** [comment]
Glad to help out :), this is an interesting project.  

As an aside, I'm thinking that some color, gradient, timing, etc. helpers might make it easier to build out complex properties.  Would you rather me write that up as a dependent library or put pull requests through here?

**Comment by basarat** [comment]
> I'm thinking that some color, gradient, timing, etc. helpers might make it easier to build out complex properties

I agree 100% :rose:

> Would you rather me write that up as a dependent library 

Dependent library. I already have helpers for creating box stuff like `padding,margin,border` in CSX : https://github.com/typestyle/csx/blob/fd1831a5357b24fec3541e6f25a6090357b273d2/csx.ts#L343-L368

I strongly believe that typestyle will only be successful if it comes with such patterns (helpers) along with the core (this package) so would love to have them all under https://github.com/typestyle

That said, do you think we should put it all into csx? Any thoughts on package structure organisation for csx? Its currently just one file : https://github.com/typestyle/csx/blob/fd1831a5357b24fec3541e6f25a6090357b273d2/csx.ts#L1 Perhaps I need to reorganize it as `csx` (everything) `csx/flex` `csx/box` `csx/layer` `csx/color` etc?

I also wish to organize this document https://github.com/typestyle/csx/blob/gh-pages/docs/README.md into a gitbook

**Comment by notoriousb1t** [comment]
I have some interesting ideas on how we could create helpers that enforce type safety that the core can validate.  I'll create a PR so you can review.  I basically built up until I was able to support a linear function.

I was able to do something clever with literal string types and generics to make it possible to keep the hsl function from working in backgroundImage and the linear-gradient function from working in backgroundColor. 

I think csx could house everything and that a modular structure makes sense.  It is important I think for sanity to try to mirror and name things the same as the CSS specs.

**Comment by basarat** [comment]
> I was able to do something clever with literal string types and generics to make it possible to keep the hsl function from working in backgroundImage and the linear-gradient function from working in backgroundColor

Nicely done :heart: It is essentially another pattern you have found for *nominal* typing. I've added to the chapter in TypeScript deep dive as its better than the ones I've found till now : https://basarat.gitbooks.io/typescript/content/docs/tips/nominalTyping.html :rose: 

>  It is important I think for sanity to try to mirror and name things the same as the CSS specs.

100% whenever pointable to a spec :rose:

**Pull request merged**
