### PR TITLE
Add ES2015 builds

### PR DESCRIPTION
**Pull request by TylorS**
Sets up ES2015 build system and adds `module` and `jsnext:main` fields to the package.json for maximum compatibility among ES2015-aware bundlers as discussed in #69.

Let me know what else I can do to help get this merged! Thanks again :smile:

### CODE REVIEW

**Comment by basarat** [comment]
I am happy to merge this :heart:. Note that if we merge this future support for `import * as something from "typestyle/lib/something"` a bit more complex (blake's comment here https://github.com/blakeembrey/free-style/issues/45#issuecomment-266489932 `if someone uses deep requires.`) I don't feel like adding more stuff to typestyle anymore anyways so not a biggie for typestyle :heart: 

@notoriousb1t you happy too? 

@TylorS no matter what the outcome. Highly appreciate you sharing this with me :rose:

**Comment by TylorS** [comment]
@basarat What we seem to be doing for free-style is creating a separate build folder for the es2015 builds. 

commonjs -> `dist/`
es2015 -> `dist.es2015/`

Would you be interested in doing the same here? Probably switching `dist` for `lib`, it wont break the current requires in `lib/`

**Comment by basarat** [comment]
Reason for `lib` (vs dist) is because other ESNext -> ESNow projects seem to be doing this e.g. https://github.com/FormidableLabs/react-animations#usage `import fadeIn from 'react-animations/lib/fade-in'`

Not overly concerned about what you call the `es2015` build. Reading rollup docs `.es2015.js` is not something that TypeScript can do https://github.com/rollup/rollup/wiki/jsnext:main

 Anything that seems conventional in other projects is fine by me. `lib.es2015` seems reasonable :rose:

**Comment by TylorS** [comment]
I updated this to match the direction we're going in `free-style`, which reverts the commonjs build back to being at just `lib/` instead of `lib/commonjs` and moves the es2015 build to `lib.es2015` :smile:

**Comment by notoriousb1t** [comment]
I'm happy with this. 😄   With csx and csstips in their own projects, I don't know that we have much of a need for deep requires.  A side note, maybe we should move test out of src to top level since it shouldn't really be distributed anyway.

**Comment by basarat** [comment]
Love the simplicity of the changeset https://github.com/typestyle/typestyle/pull/71/files :rose:

**Comment by basarat** [comment]
> A side note, maybe we should move test out of src to top level since it shouldn't really be distributed anyway.

Agree. `.npmignore` needs love. Will create a seperate issue we should work on elsewhere after this :) https://github.com/typestyle/typestyle/blob/master/.npmignore

**Comment by basarat** [comment]
@TylorS let me know whenever you want this released. I will merge and release as a `minor` version :rose:

**Comment by TylorS** [comment]
@basarat Additionally you can distribute only specific files using the `files` field in the package.json instead of wrangling with the `.npmignore`

**Comment by TylorS** [comment]
Link: https://docs.npmjs.com/files/package.json#files

**Comment by TylorS** [comment]
> let me know whenever you want this released

It may make some sense to wait for free-style's changes to be merged?

**Comment by basarat** [comment]
> It may make some sense to wait for free-style's changes to be merged?

Cool. I agree 💯. Just empathising with your amazing effort. Will wait :rose:

**Comment by basarat** [comment]
I wonder if type augmentation for people building with es2015? http://typestyle.io/#/core/tip-declaring-new-css-stuff

**Comment by TylorS** [comment]
Good question! I'll try and see if it is possible, and how it might work :+1:

**Comment by TylorS** [comment]
@basarat Its 100% identical to what is in the docs :)

https://github.com/TylorS/typestyle-es2015-experiment

Some crappy instructions are in the README if you want to try it out yourself. 
As I suspected, because the `typings` field in the package.json has been untouched and points to `lib/index` it continues to work exactly as before :)

**Comment by basarat** [comment]
Merging as I am about to do a minor upgrade and good to get some usage on this in the wild :rose:

**Comment by basarat** [comment]
Minor : will strip declaration for es2015 builds as the only `.d.ts` that matters will be the one in `lib` :rose:

**Comment by TylorS** [comment]
Yay, thanks everyone :heart: 

Will try to do the same for csx and csstips this week :)

**Comment by basarat** [comment]
Released with `0.19.0` :rose:

**Pull request merged**
