### PR TITLE
vendor prefixes

### PR DESCRIPTION
**Pull request by notoriousb1t**
Added vendor prefixes.  There are over 400 vendor prefixes.   Should we take these wholesale, or try to pare them down @basarat?

### CODE REVIEW

**Comment by basarat** [comment]
Wholesale sounds great. Most of these will be irrelevant in two years for sure (if not already) 🌹

Feel free to merge / cut a release

**Comment by notoriousb1t** [comment]
I have most of these as any, what do you think about starting narrowing to string?  I think it is safe to say that they could be expressed as a string.

**Comment by basarat** [comment]
I think CSSValueGeneral already exists 🌹

**Comment by basarat** [comment]
On the phone 😀

**Comment by notoriousb1t** [comment]
Ah, yes.  Will change them that

**Pull request merged**
