### PR TITLE
Added more types and properties

### PR DESCRIPTION
**Pull request by markvandenbrink**
Added property:
- `captionSide`

Added types for:
- `backfaceVisibility`
- `breakAfter`
- `breakBefore`
- `breakInside`
- `clear`
- `fontStretch`
- `fontStyle`
- `textOverflow`
- `touchAction`
- `verticalAlign`
- `visibility`
- `wordBreak`
- `wordSpacing`

Added 'auto' to possible values for:
- `width`
- `height`
- `left`
- `right`
- `bottom`
- `top`

### CODE REVIEW

**Comment by basarat** [comment]
Merge yourself whenever ready please :rose: 

Let me know your npm name and we can give you publish access as well. Release as a patch if API doesn't have a breaking change. 

It might be 12 hours before I use the computer again. Good night for now :rose:

**Comment by basarat** [comment]
Don't want to hold this off. Releasing :rose:

**Comment by basarat** [comment]
`0.18.2` :heart:

**Comment by markvandenbrink** [comment]
Thanks for merging! Haven't had much time last few days... I will do #61 as soon as possible.

My npm handle is `markvandenbrink`.

**Comment by basarat** [comment]
Cheers. Added access :rose:

**Pull request merged**
